import { useMemo, useState } from "react";
import {
  Search,
  CircleHelp,
  LayoutDashboard,
  Percent,
  ShoppingCart,
  KeyRound,
  FileBarChart,
  Users,
  Star,
  ChevronRight,
  ExternalLink,
  ShieldCheck,
  FileText,
  SeparatorHorizontal,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const categories = [
  {
    title: "Product Management",
    description:
      "Manage products, product details, pricing, and stock information easily.",
    icon: LayoutDashboard,
    articles: 10,
  },
  {
    title: "Categories & Discounts",
    description:
      "Create product categories and manage discount offers or promotions.",
    icon: Percent,
    articles: 8,
  },
  {
    title: "Orders, Rent & Lease",
    description:
      "Track and manage orders, rent requests, and lease activities in one place.",
    icon: ShoppingCart,
    articles: 12,
  },
  {
    title: "Transactions & Reports",
    description:
      "View transactions and generate reports by day, month, year, or custom date.",
    icon: FileBarChart,
    articles: 9,
  },
  {
    title: "Customers & Enquiries",
    description:
      "Manage customer records and respond to enquiries efficiently.",
    icon: Users,
    articles: 7,
  },
  {
    title: "Reviews & Security",
    description:
      "Manage product reviews, portal settings, and account security options.",
    icon: ShieldCheck,
    articles: 11,
  },
  {
    title: "Profile & Password",
    description:
      " Use the Change Password option in your profile to update your password securely.",
    icon: KeyRound,
    articles: 11,
  },
];

const popularArticles = [
  "How to add and manage products",
  "How to create product categories",
  "How to apply discounts to products",
  "How to manage orders, rent, and lease requests",
  "How to generate reports by month, year, and custom date",
  "How to change your password from profile settings",
];

const faqs = [
  {
    question: "What can I manage from the ADADA Chai Admin Portal?",
    answer:
      "You can manage products, categories, discounts, orders, rent, lease, transactions, reports, customers, enquiries, and product reviews from this portal.",
  },
  {
    question: "Can I generate reports using a custom date range?",
    answer:
      "Yes. Reports can be generated by day, month, year, and also by using a custom date range.",
  },
  {
    question: "How do I change my password?",
    answer:
      "Go to your Profile section and use the Change Password option to update your password securely.",
  },
  {
    question: "Does the portal support dark mode?",
    answer:
      "Yes. The portal supports dark mode, light mode, and system default mode.",
  },
  {
    question: "Can I manage customer enquiries and product reviews?",
    answer:
      "Yes. You can manage customer enquiries and monitor product reviews directly from the admin portal.",
  },
];

export default function HelpCenterPage() {
  const [query, setQuery] = useState("");

  const filteredArticles = useMemo(() => {
    if (!query.trim()) return popularArticles;

    return popularArticles.filter((article) =>
      article.toLowerCase().includes(query.toLowerCase()),
    );
  }, [query]);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-full space-y-8 px-4 py-6 sm:px-6 lg:px-8">
        <section className="relative overflow-hidden rounded-3xl border border-border bg-gradient-to-br from-muted/50 via-background to-muted/20 p-6 shadow-sm lg:p-8">
          <div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute -bottom-10 -left-10 h-40 w-40 rounded-full bg-primary/5 blur-3xl" />

          <div className="relative z-10">
            <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Welcome to ADADA Chai Admin Portal
            </h1>

            <div className="grid gap-4 md:grid-cols-2">
              <div>
                <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">
                  This portal helps you manage products, categories, discounts,
                  orders, rent, lease, transactions, and reports in one place.
                  You can also manage customers, enquiries, and product reviews
                  easily.
                </p>

                <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">
                  Reports can be generated by day, month, year, or custom date
                  range. The portal also supports dark mode, light mode, and
                  system default settings for a better user experience.
                </p>
              </div>

              <div>
                <div className="mt-6 flex flex-col gap-3 sm:flex-row">
                  <div className="relative w-full max-w-2xl">
                    <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                    <Input
                      value={query}
                      onChange={(e) => setQuery(e.target.value)}
                      placeholder="Search portal help topics..."
                      className="h-12 rounded-2xl border-border bg-background pl-10 shadow-sm"
                    />
                  </div>
                  <Button className="h-12 rounded-2xl px-6">Search</Button>
                </div>

                <div className="mt-4 flex flex-wrap gap-2">
                  {[
                    "Products",
                    "Categories",
                    "Discounts",
                    "Reports",
                    "Customers",
                    "Change Password",
                  ].map((tag) => (
                    <Button
                      key={tag}
                      variant="outline"
                      size="sm"
                      className="rounded-full"
                    >
                      {tag}
                    </Button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-3 xl:grid-cols-4">
          {categories.map((item) => {
            const Icon = item.icon;
            return (
              <Card
                key={item.title}
                className="group rounded-3xl border-border bg-background transition-all hover:-translate-y-0.5 hover:shadow-md"
              >
                <CardContent className="flex h-full flex-col gap-4 p-6">
                  <div className="flex items-start justify-between">
                    <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                      <Icon className="h-5 w-5" />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold">{item.title}</h3>
                    <p className="text-sm text-muted-foreground">
                      {item.description}
                    </p>
                  </div>

                  <Button
                    variant="ghost"
                    className="mt-auto justify-between rounded-2xl px-0 text-sm font-medium"
                  >
                    View details
                    <ChevronRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                  </Button>
                </CardContent>
              </Card>
            );
          })}
        </section>

        <section className="grid">
          <Card className="rounded-3xl border-border">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CircleHelp className="h-5 w-5" />
                Frequently asked questions
              </CardTitle>
              <CardDescription>
                Quick answers to common questions about the admin portal.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={faq.question} value={`item-${index}`}>
                    <AccordionTrigger className="text-left text-sm font-medium">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-sm leading-6 text-muted-foreground">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </section>

        <section>
          <Card className="rounded-3xl border-border bg-muted/30">
            <CardContent className="flex flex-col gap-5 p-6 lg:flex-row lg:items-center lg:justify-between">
              <div>
                <h3 className="text-xl font-semibold">Need more help?</h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Contact the support team for help with reports, transactions,
                  settings, or account access.
                </p>
              </div>

              <div className="flex flex-col gap-3 sm:flex-row">
                <Button className="rounded-2xl px-6">Contact Support</Button>
              </div>
            </CardContent>
          </Card>
        </section>

        <Separator />

        <section className="pb-4">
          <p className="text-center text-sm text-muted-foreground">
            ADADA Chai Admin Portal • Help & Support • Reports • Security •
            Profile Settings
          </p>
        </section>
      </div>
    </div>
  );
}
